name: Build new release
on:
  schedule:
    - cron: "0 6 * * *" # every day at 06:00 AM
  workflow_dispatch: {}

jobs:
  check_release:
    name: Check for new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check for updated package
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RAW=$(gh release ls -R jj-vcs/jj -L 1 --json tagName --template '{{index . 0 "tagName"}}')
          LATEST=$(echo ${LATEST_RAW#v})
          CURRENT_RAW=$(cat jj-cli.spec | grep "Version:")
          CURRENT=$(echo ${CURRENT_RAW#Version:})

          echo "Latest: $LATEST"
          echo "Current: $CURRENT"

          if [ "x${LATEST}" != "x${CURRENT}" ]; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Update spec
        if: ${{ steps.check.outputs.updated }}
        run: |
          sed -i "s/${CURRENT}/${LATEST}/" jj-cli.spec
          sed -i -E "s/^(Release: *).*$/\11%{?dist}/" jj-cli.spec
          git add jj-cli.spec
          git -c user.name=web-flow -c user.email=noreply@github.com commit -m "update to ${LATEST}"
          git push
